# Generated by Django 5.2.1 on 2025-10-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='nombre', max_length=45, null=True)),
                ('address', models.CharField(blank=True, db_column='direccion', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=45, null=True)),
                ('phone', models.CharField(blank=True, db_column='telefono', max_length=10, null=True)),
                ('opening_time', models.TimeField(blank=True, db_column='horario_apertura', null=True)),
                ('closing_time', models.TimeField(blank=True, db_column='horario_cierre', null=True)),
                ('logo', models.CharField(blank=True, db_column='logo', max_length=255, null=True)),
                ('status', models.BooleanField(blank=True, db_column='estatus', null=True)),
            ],
            options={
                'db_table': 'restaurantes',
            },
        ),
    ]
