# Generated by Django 5.2.1 on 2025-11-01 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
    ]
