# Generated by Django 5.2.1 on 2025-11-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20251101_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='account_number',
            field=models.CharField(blank=True, db_column='numero_cuenta', help_text='Número de cuenta bancaria', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='clabe',
            field=models.CharField(blank=True, db_column='clabe', help_text='CLABE interbancaria', max_length=20, null=True),
        ),
    ]
