# Generated by Django 5.2.1 on 2025-11-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], db_column='metodo_pago', help_text='Método de pago (efectivo o transferencia)', max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado'), ('reembolsado', 'Reembolsado')], db_column='estatus', default='pendiente', help_text='Estado del pago (pendiente, confirmado, rechazado o reembolsado)', max_length=20, null=True)),
                ('amount', models.DecimalField(blank=True, db_column='monto', decimal_places=2, help_text='Monto total del pago', max_digits=10, null=True)),
                ('receipt', models.CharField(blank=True, db_column='comprobante', help_text='Comprobante del pago (URL o texto)', max_length=255, null=True)),
                ('payment_date', models.DateTimeField(blank=True, db_column='fecha_pago', help_text='Fecha y hora del pago', null=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'pagos',
                'ordering': ['-payment_date'],
                'managed': False,
            },
        ),
    ]
