# Generated by Django 5.2.1 on 2025-11-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(
                auto_now_add=True,
                db_column='fecha_pago',
                help_text='Fecha y hora del pago',
            ),
        ),
    ]
