# Generated by Django 5.2.1 on 2025-11-09 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_arrival_time'),
        ('payments', '0002_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, db_column='ordenId', help_text='Orden asociada al pago', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='orders.order'),
        ),
    ]
