# Generated by Django 5.2.1 on 2025-10-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='nombre', max_length=100, null=True)),
                ('description', models.CharField(blank=True, db_column='descripcion', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
            ],
            options={
                'db_table': 'estatus_ordenes',
            },
        ),
    ]
