# Generated by Django 5.2.1 on 2025-10-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=45)),
                ('lastname', models.CharField(db_column='apellido', max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('phone', models.CharField(db_column='telefono', max_length=10)),
                ('image', models.CharField(db_column='imagen', max_length=255, null=True)),
                ('password', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(db_column='fecha_creacion', null=True)),
                ('updated_at', models.DateTimeField(db_column='fecha_actualizacion', null=True)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
    ]
