# Generated by Django 5.2.1 on 2025-10-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.URLField(max_length=60),
        ),
    ]
