# Generated by Django 5.2.1 on 2025-10-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.URLField(db_column='imagen', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=60),
        ),
    ]
