# Generated by Django 5.2.1 on 2025-10-04 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='nombre', max_length=100, null=True)),
                ('description', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('image', models.CharField(blank=True, db_column='imagen', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('id_restaurant', models.ForeignKey(blank=True, db_column='restauranteId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
    ]
