# Generated by Django 5.2.1 on 2025-10-07 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_alter_client_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(blank=True, db_column='alias', max_length=100, null=True)),
                ('address', models.CharField(blank=True, db_column='direccion', max_length=255, null=True)),
                ('reference', models.CharField(blank=True, db_column='referencia', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('id_client', models.ForeignKey(db_column='clienteId', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='clients.client')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'direcciones',
            },
        ),
    ]
