# Generated by Django 5.2.1 on 2025-10-12 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('clients', '0003_alter_client_email'),
        ('orderstatus', '0001_initial'),
        ('products', '0002_rename_category_product_id_category'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('order_type', models.CharField(blank=True, choices=[('sitio', 'Sitio'), ('domicilio', 'Domicilio'), ('anticipado', 'Anticipado')], db_column='tipo_pedido', max_length=20, null=True)),
                ('note', models.TextField(blank=True, db_column='nota', null=True)),
                ('address', models.ForeignKey(blank=True, db_column='direccionId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='address.address')),
                ('client', models.ForeignKey(blank=True, db_column='clienteId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='clients.client')),
                ('restaurant', models.ForeignKey(blank=True, db_column='restauranteId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurants.restaurant')),
                ('status', models.ForeignKey(blank=True, db_column='estatusId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orderstatus.orderstatus')),
            ],
            options={
                'db_table': 'ordenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('order', models.ForeignKey(db_column='ordenId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='orderdetails', serialize=False, to='orders.order')),
                ('quantity', models.IntegerField(db_column='cantidad')),
                ('unit_price', models.DecimalField(db_column='precio_unitario', decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(db_column='productoId', on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='products.product')),
            ],
            options={
                'db_table': 'detalles_ordenes',
                'unique_together': {('order', 'product')},
            },
        ),
    ]
