# Generated by Django 5.2.1 on 2025-10-17 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderdetail_unique_together_and_more'),
    ]

    operations = [
    ]
