# Generated by Django 5.2.1 on 2025-10-17 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderdetail_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(db_column='ordenId', on_delete=django.db.models.deletion.CASCADE, related_name='orderdetails', to='orders.order'),
        ),
    ]
