# Generated by Django 5.2.1 on 2025-10-17 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderdetail_id_alter_orderdetail_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'managed': True, 'ordering': ['id']},
        ),
    ]
