# Generated by Django 5.2.1 on 2025-10-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderdetail_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arrival_time',
            field=models.TimeField(blank=True, db_column='hora_llegada', help_text='Hora de llegada para órdenes anticipadas (15:00–23:00)', null=True),
        ),
    ]
