# Generated by Django 5.2.1 on 2025-10-05 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='nombre', max_length=100, null=True)),
                ('description', models.CharField(blank=True, db_column='descripcion', max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, db_column='precio', decimal_places=2, max_digits=10, null=True)),
                ('image1', models.CharField(blank=True, db_column='imagen1', max_length=255, null=True)),
                ('image2', models.CharField(blank=True, db_column='imagen2', max_length=255, null=True)),
                ('available', models.BooleanField(blank=True, db_column='disponible', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='fecha_creacion', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='fecha_actualizacion', null=True)),
                ('category', models.ForeignKey(blank=True, db_column='categoriaId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
