# Generated by Django 5.2.1 on 2025-11-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_category_product_id_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deleted',
            field=models.BooleanField(db_column='eliminado', default=False),
        ),
    ]
